name: Run Notion Auto Progress

on:
  schedule:
    - cron: "0 1 * * *"  # 每天台灣時間早上 9 點執行
  workflow_dispatch:     # 允許手動觸發

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Notion SDK
        run: pip install notion-client

      - name: Install pytz  # ⬅️ 加這一段即可解決問題
        run: pip install pytz

      - name: Run main.py
        run: python main.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          PAGEID_MEETING_1: ${{ secrets.PAGEID_MEETING_1 }}
          DBID_MEETING_1: ${{ secrets.DBID_MEETING_1 }}

#force update cron registration
